# ==============================================================
# pynq_z2.xdc  —  Timing Constraints for PYNQ-Z2
#
# Target: xc7z020clg400-1
# FCLK_CLK0 = 100 MHz (set in Zynq PS properties)
# ==============================================================

# ── Primary clock (generated by Zynq PS FCLK_CLK0) ───────────
# This is a virtual constraint; the actual clock comes from PS7.
# Vivado infers it from the block design automatically.
# The line below is a safety fallback for RTL-only simulation.
# create_clock -period 10.000 -name clk_100MHz [get_ports clk]

# ── False Paths across async clock domains ────────────────────
# (None needed: single clock domain design)

# ── Input/Output delays (AXI-Stream — relaxed for 100 MHz) ───
# DMA-controlled streams: timing managed by Zynq IP internally.

# ── Bitstream settings ───────────────────────────────────────
set_property BITSTREAM.GENERAL.COMPRESS   TRUE  [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4     [current_design]
set_property CONFIG_VOLTAGE               3.3   [current_design]
set_property CFGBVS                       VCCO  [current_design]

# ── ILA / Mark-debug (optional: comment out if not debugging) ──
# Vivado automatically picks up (*mark_debug="true"*) attributes
# from RTL. To use ILA, enable debug in implementation settings.
