# ==============================================================
# 01_gen_protected_rtl.tcl
#
# Reads DESIGN_N, DESIGN_D_W, DESIGN_DATAFLOW, PE_PROTECTION_MAP
# from design_config.tcl (must be sourced first) and generates:
#
#   vivado_build/generated/systolic_protected.sv
#
# The generated module has the same interface as systolic.sv PLUS:
#   output wire fault_flag   (OR of all DMR error_flag signals)
#
# Supported dataflows (set DESIGN_DATAFLOW in design_config.tcl):
#   "OS"  → Output Stationary  : uses pe     / pe_dmr     / pe_tmr
#   "WS"  → Weight Stationary  : uses pe_ws  / pe_ws_dmr  / pe_ws_tmr
#   "IS"  → Input  Stationary  : uses pe_is  / pe_is_dmr  / pe_is_tmr
#
# PE module naming convention per dataflow:
#   OS:  base="pe",    dmr_wrap="pe_dmr",    tmr_wrap="pe_tmr"
#   WS:  base="pe_ws", dmr_wrap="pe_ws_dmr", tmr_wrap="pe_ws_tmr"
#   IS:  base="pe_is", dmr_wrap="pe_is_dmr", tmr_wrap="pe_is_tmr"
# ==============================================================

set N   $DESIGN_N
set M   $DESIGN_N    ;# M = N, FIXED
set DW  $DESIGN_D_W
set DF  $DESIGN_DATAFLOW

# ── Validate dataflow ─────────────────────────────────────────
if {$DF ni {"OS" "WS" "IS"}} {
    error "ERROR: DESIGN_DATAFLOW must be OS, WS, or IS (got: '$DF')"
}

# ── Set PE module names based on dataflow ─────────────────────
switch $DF {
    "OS" {
        set pe_base "pe"
        set pe_dmr  "pe_dmr"
        set pe_tmr  "pe_tmr"
    }
    "WS" {
        set pe_base "pe_ws"
        set pe_dmr  "pe_ws_dmr"
        set pe_tmr  "pe_ws_tmr"
    }
    "IS" {
        set pe_base "pe_is"
        set pe_dmr  "pe_is_dmr"
        set pe_tmr  "pe_is_tmr"
    }
}

# ── Build PE protection lookup table ─────────────────────────
array set pe_mode {}
for {set r 0} {$r < $N} {incr r} {
    for {set c 0} {$c < $N} {incr c} {
        set pe_mode($r,$c) "none"
    }
}
foreach entry $PE_PROTECTION_MAP {
    set r [lindex $entry 0]
    set c [lindex $entry 1]
    set m [lindex $entry 2]
    if {$r >= $N || $c >= $N} {
        puts "WARNING: PE($r,$c) out of range for N=$N — skipped."
        continue
    }
    set pe_mode($r,$c) $m
}

# ── Count DMR PEs ─────────────────────────────────────────────
set dmr_list {}
for {set r 0} {$r < $N} {incr r} {
    for {set c 0} {$c < $N} {incr c} {
        if {$pe_mode($r,$c) eq "DMR"} { lappend dmr_list "${r}_${c}" }
    }
}
set num_dmr [llength $dmr_list]
set num_tmr 0
foreach entry $PE_PROTECTION_MAP {
    if {[lindex $entry 2] eq "TMR"} { incr num_tmr }
}

# ── Open output file ──────────────────────────────────────────
set gen_dir [file join [file dirname [file normalize [info script]]] "../generated"]
file mkdir $gen_dir
set out_path [file join $gen_dir "systolic_protected.sv"]
set fh [open $out_path w]
proc w {line} { global fh; puts $fh $line }

# ── Header & module declaration ───────────────────────────────
w "`timescale 1ns / 1ps"
w "// AUTO-GENERATED by 01_gen_protected_rtl.tcl — DO NOT EDIT MANUALLY"
w "// Dataflow : $DF  |  N=$N  M=$M  D_W=$DW"
w "// PE base  : $pe_base  (DMR: $pe_dmr  TMR: $pe_tmr)"
w "// Protection map: [llength $PE_PROTECTION_MAP] entries, $num_tmr TMR, $num_dmr DMR"
w ""
w "module systolic_protected"
w "#("
w "    parameter D_W = $DW,"
w "    parameter N   = $N,"
w "    parameter M   = $M"
w ")("
w "    input  wire                       clk,"
w "    input  wire                       rst,"
w "    input  wire                       enable_row_count_m0,"
w "    output wire \[\$clog2(M)-1:0\]      column_m0,"
w "    output wire \[\$clog2(M/N)-1:0\]    row_m0,"
w "    output wire \[\$clog2(M/N)-1:0\]    column_m1,"
w "    output wire \[\$clog2(M)-1:0\]      row_m1,"
w "    input  wire \[D_W-1:0\]             m0 \[N-1:0\],"
w "    input  wire \[D_W-1:0\]             m1 \[N-1:0\],"
w "    output wire \[2*D_W-1:0\]          m2 \[N-1:0\],"
w "    output wire \[N-1:0\]              valid_m2,"
w "    output wire                       fault_flag"
w ");"
w ""

# ── Counter instances (same for all dataflows) ───────────────
w "// ── Address counters (identical to systolic.sv) ──────────"
w "counter #(.WIDTH(M), .HEIGHT(M/N)) counter_m1 ("
w "    .clk(clk), .rst(rst), .enable_row_count(1'b1),"
w "    .column_counter(row_m1), .row_counter(column_m1));"
w ""
w "counter #(.WIDTH(M), .HEIGHT(M/N)) counter_m0 ("
w "    .clk(clk), .rst(rst), .enable_row_count(enable_row_count_m0),"
w "    .column_counter(column_m0), .row_counter(row_m0));"
w ""

# ── Init signal generator (diagonal wavefront — same for all) ─
w "// ── Diagonal wavefront init generator ────────────────────"
w "// The init signal serves different purposes per dataflow:"
switch $DF {
    "OS" { w "// OS: init=1 flushes the PE accumulator  and starts a new psum" }
    "WS" { w "// WS: init=1 triggers weight LOAD into w_reg from in_b" }
    "IS" { w "// IS: init=1 triggers activation LOAD into a_reg from in_a" }
}
w "// The same diagonal timing ensures PE\[r\]\[c\] fires at r+c==slice,"
w "// matching the skewed arrival of data on HorizontalWire/VerticalWire."
w "integer slice, i, j;"
w "reg init\[N-1:0\]\[N-1:0\];"
w ""
w "always@(posedge clk) begin"
w "    if(rst == 1) begin"
w "        slice <= 2*N-1;"
w "        for(i=0;i<N;i=i+1) for(j=0;j<N;j=j+1) init\[i\]\[j\] <= 0;"
w "    end else begin"
w "        for(i=0;i<N;i=i+1) for(j=0;j<N;j=j+1) init\[i\]\[j\] <= 0;"
w "        if(column_m0 == M-1) slice <= 0;"
w "        if(slice < 2*N-1) begin"
w "            for(i=0;i<N;i=i+1)"
w "                for(j=0;j<N;j=j+1)"
w "                    if(i+j==slice) init\[i\]\[j\] <= 1;"
w "                    else           init\[i\]\[j\] <= 0;"
w "            slice <= slice+1;"
w "        end"
w "    end"
w "end"
w ""

# ── Wire mesh ─────────────────────────────────────────────────
w "// ── Interconnect mesh (same topology for all dataflows) ──"
w "wire \[D_W-1:0\]   HorizontalWire\[N:0\]\[N:0\];  // in_a → out_a (left to right)"
w "wire \[D_W-1:0\]   VerticalWire\[N:0\]\[N:0\];    // in_b → out_b (top to bottom)"
w "wire \[2*D_W-1:0\] OutputDataWire\[N:0\]\[N:0\];  // psum chain  (left to right)"
w "wire             OutputValidWire\[N:0\]\[N:0\];"
w ""
w "genvar k;"
w "generate"
w "for(k=0;k<N;k=k+1) begin : boundary"
w "    assign HorizontalWire\[k\]\[0\] = m0\[k\];   // m0 → row inputs"
w "    assign VerticalWire\[0\]\[k\]   = m1\[k\];   // m1 → col inputs"
w "    assign OutputDataWire\[k\]\[0\] = 0;"
w "    assign OutputValidWire\[k\]\[0\]= 0;"
w "    assign m2\[k\]       = OutputDataWire\[k\]\[N\];   // result from rightmost col"
w "    assign valid_m2\[k\] = OutputValidWire\[k\]\[N\];"
w "end"
w "endgenerate"
w ""

# ── Fault flag wiring ─────────────────────────────────────────
w "// ── DMR fault flag collection ─────────────────────────────"
if {$num_dmr > 0} {
    foreach id $dmr_list { w "wire fault_${id};" }
    set terms [lmap id $dmr_list { set _ "fault_${id}" }]
    w "assign fault_flag = [join $terms \" | \"];"
} else {
    w "assign fault_flag = 1'b0; // No DMR PEs in this configuration"
}
w ""

# ── PE instantiations ─────────────────────────────────────────
w "// ── PE grid instantiation ─────────────────────────────────"
w "// Dataflow: $DF"
w "// Base PE  : $pe_base"
for {set r 0} {$r < $N} {incr r} {
    for {set c 0} {$c < $N} {incr c} {
        set mode $pe_mode($r,$c)
        set inst "pe_${r}_${c}"
        set cnx ".clk(clk), .rst(rst), .init(init\[$r\]\[$c\]),
      .in_a(HorizontalWire\[$r\]\[$c\]),
      .in_b(VerticalWire\[$r\]\[$c\]),
      .out_a(HorizontalWire\[$r\]\[[expr {$c+1}]\]),
      .out_b(VerticalWire\[[expr {$r+1}]\]\[$c\]),
      .in_data(OutputDataWire\[$r\]\[$c\]),
      .in_valid(OutputValidWire\[$r\]\[$c\]),
      .out_data(OutputDataWire\[$r\]\[[expr {$c+1}]\]),
      .out_valid(OutputValidWire\[$r\]\[[expr {$c+1}]\])"

        switch $mode {
            "TMR" {
                w "$pe_tmr #(.D_W(D_W),.i($r),.j($c)) $inst ("
                w "    $cnx);"
            }
            "DMR" {
                w "$pe_dmr #(.D_W(D_W),.i($r),.j($c)) $inst ("
                w "    $cnx,"
                w "    .error_flag(fault_${r}_${c}));"
            }
            default {
                w "$pe_base #(.D_W(D_W),.i($r),.j($c)) $inst ("
                w "    $cnx);"
            }
        }
        w ""
    }
}

w "endmodule"
close $fh

puts "  ✓ Generated: $out_path"
puts "    Dataflow=$DF  N=$N  TMR PEs=$num_tmr  DMR PEs=$num_dmr"
puts "    Base PE: $pe_base | DMR wrap: $pe_dmr | TMR wrap: $pe_tmr"
