`timescale 1ns / 1ps
// ============================================================
// pe_is.v  —  Input Stationary Processing Element
//
// DATAFLOW ANALYSIS (vs OS and WS):
// ┌────────────────┬──────────────────┬──────────────────────┐
// │                │   WS (pe_ws)     │   IS  (pe_is.v)      │
// ├────────────────┼──────────────────┼──────────────────────┤
// │ Stationary     │ Weight (B)       │ Input Activation (A) │
// │ Register       │ w_reg            │ a_reg                │
// │ in_a role      │ Activation flows │ Activation LOAD only │
// │ in_b role      │ Weight LOAD only │ Weight flows         │
// │ out_a          │ A pass-through   │ A pass-through*      │
// │ out_b          │ B pass-through   │ B pass-through       │
// │ psum path      │ flows RIGHT      │ flows RIGHT          │
// │ init=1 means   │ load in_b as W   │ load in_a as A       │
// └────────────────┴──────────────────┴──────────────────────┘
//
// * out_a passes in_a through so diagonal loading can fill
//   deeper columns of the systolic array.
//
// OPERATION SEQUENCE:
//   Phase 1 (LOAD, N cycles):
//     init=1; in_a carries one activation element per cycle
//     → PE[r][c] captures its a_reg when init[r][c] fires
//     → same diagonal wavefront as OS/WS (generated by systolic)
//
//   Phase 2 (COMPUTE, M cycles per tile):
//     init=0; in_b carries weight elements (B matrix columns)
//     → weights flow VERTICALLY (down via VerticalWire)
//     → PE computes:  psum_out = psum_in + a_reg * B_pipe
//     → partial sum flows RIGHT via OutputDataWire
//     → right edge collects dot product result
//
// MATHEMATICAL RESULT:
//   m2[r] = sum_{c=0}^{N-1}  A_loaded[r][c] * B[c][r_step]
//   (inner product of loaded A row with each column fragment of B)
//   Full C = A × B^T is obtained by pipelining tiles.
//   NOTE: B is effectively transposed vs OS flow.
//         Pre-transpose B in software before sending to PL,
//         OR use IS explicitly when B^T is the desired multiplication.
// ============================================================
module pe_is
#(
    parameter D_W = 8,
    parameter i   = 0,
    parameter j   = 0
)(
    input  wire              clk,
    input  wire              rst,
    input  wire              init,       // 1 = LOAD phase, 0 = COMPUTE phase
    input  wire [D_W-1:0]   in_a,       // activation A (LOAD when init=1)
    input  wire [D_W-1:0]   in_b,       // weight B (flows vertically during COMPUTE)
    output wire [D_W-1:0]   out_a,      // A pass-through to next column (for loading)
    output wire [D_W-1:0]   out_b,      // B pass-through to next row
    input  wire [2*D_W-1:0] in_data,    // incoming partial sum from left
    input  wire              in_valid,
    output reg  [2*D_W-1:0] out_data,   // outgoing partial sum to right
    output reg               out_valid
);

    // ── Internal registers ────────────────────────────────────
    reg [D_W-1:0]   a_reg;          // STATIONARY input activation
    reg [D_W-1:0]   a_pipe;         // pipeline register for out_a pass-through
    reg [D_W-1:0]   b_pipe;         // pipeline register for in_b
    reg [2*D_W-1:0] product_r;      // registered product: a_reg * b_pipe
    reg [2*D_W-1:0] in_data_r;
    reg             in_valid_r;
    reg             init_r;

    always @(posedge clk) begin
        if (rst) begin
            a_reg      <= 0;  a_pipe   <= 0;  b_pipe   <= 0;
            product_r  <= 0;  in_data_r<= 0;  in_valid_r<= 0;
            init_r     <= 0;  out_data <= 0;   out_valid <= 0;
        end else begin
            // ── Pipeline stage 1: register inputs ─────────────
            a_pipe     <= in_a;
            b_pipe     <= in_b;
            in_data_r  <= in_data;
            in_valid_r <= in_valid;
            init_r     <= init;

            // ── Activation capture (LOAD phase) ───────────────
            //    Diagonal wavefront: init[r][c] fires when r+c==slice
            //    Each PE captures its activation at its own init pulse
            if (init)
                a_reg <= in_a;

            // ── Pipeline stage 2: compute product ────────────
            // a_reg is stationary; in_b (weight) flows through
            product_r <= a_reg * in_b;

            // ── Pipeline stage 3: accumulate / pass ──────────
            if (!init_r) begin
                // COMPUTE phase: add product to incoming psum
                out_data  <= in_data_r + product_r;
                out_valid <= in_valid_r;
            end else begin
                // LOAD phase: zero out the psum chain
                out_data  <= 0;
                out_valid <= 0;
            end
        end
    end

    // ── Pass-throughs ─────────────────────────────────────────
    assign out_a = a_pipe;   // activation routes to next column for loading
    assign out_b = b_pipe;   // weight continues down to next row

endmodule
